### ISSUE TITLE
Chapter 5

### ISSUE THREAD

**Issue by gduquesnay** [rails3book/ticketee-old#3]
Hey Ryan,

We cloned and checkout out chapter 5 but running bundle exec cucumber fails unless we comment out line 18 of features/support/env.rb : require 'cucumber/rails/capybara_javascript_emulation' # Lets you click links with onclick javascript handlers without using @culerity

I think this might be a known issue but we are still getting it so I thought I'd mention it.

Regards

Korean Ruby Group

**Comment by radar** [comment]
Thanks for pointing this out.

I'm aware of the issue but I'm not sure of a correct work around. I seem to recall a patch for Cucumber or Capybara about it but I'm not sure if either of those two projects have patched the issue. I am keeping a close eye on the issue but will now leave a comment in Chapter 3 which fixes this.

**Comment by radar** [comment]
Here's a screenshot of the comment from Twist (the review system we use for the book):

https://img.skitch.com/20110115-gt7y81m2b7fueeay61fexsh886.png

Done good?

**Comment by gduquesnay** [comment]
Yep thanks.

Wow really quick responses on issues!  You guys are awesome.  Keep up the good work.
